### ISSUE TITLE
varible in volume name in docker-compose

### ISSUE THREAD

**Issue by fahimeh2010** [CWSpear/local-persist#21]
Hello all
Fist thank you for your open source project.
I have one docker-compose like this:

```yaml
version '2'
 services:
   image:nginx
   volumes:
      - nginx-config:/etc/nginx
volumes:
    nginx-config:
       driver: local-persist
       driver_opts:
          mountpoint : /path/on/host
```

 but I want o have an variable in name local-persist volume, like this:

```yaml
version '2'
 services:
   image:nginx
   volumes:
      - ${prefix}-nginx-config:/etc/nginx
volumes:
    ${prefix}-nginx-config:
       driver: local-persist
       driver_opts:
          mountpoint : /path/on/host
```

but it returns error. is it possible and how?

Thanks a lot
