### ISSUE TITLE
Add feature to create local folders when mounting

### ISSUE THREAD

**Issue by joaocc** [CWSpear/local-persist#32]
Hi,
Have you thought of adding a feature/flag/mode to allow the creation of folder on the docker host when setting up the container and when mounting volumes?
Currently, to use local-persist in docker-compose, I need to make sure the folders exist, which in turns requires an external script.
Being able to have the folders create automatically in the docker host, we would have a smoother experience.
Thx

**Comment by joaocc** [comment]
suggestion:
```
driver_opts:
    mountpoint: /data/my/good/folder
    force_mkdir: true
    mkdir_opts:
        owner: user1
        group: group1
        mode: "u=rwx,o+rX"
```
