### ISSUE TITLE
Disadvantages of normal driver

### ISSUE THREAD

**Issue by luckydonald** [CWSpear/local-persist#45]
Hi!
I was looking at your excellent documentation, but still can't quite grasp what it does.

I understand, that you can create host directory based _default driver_ volumes like this:
```yml
# docker-compose.yml
services:
  some-service:
    volumes: 
      - /data/mysql:/var/lib/mysql
```
and that is basically the same as
```yml
# docker-compose.yml
services:
  some-service:
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/mysql
```
with this driver.
Is this different in any way?

Or does this only affect [Data volumes](https://docs.docker.com/engine/tutorials/dockervolumes/#/data-volumes), which are now stored at a known location instead something random like
```path
/data:/var/lib/docker/vfs/dir/cde167197ccc3e138a14f1a4f7c0d65b32cecbada822b0db4cc92e79059437a9
```
[(Source)](http://container-solutions.com/understanding-volumes-docker/)

Could you list/elaborate the disadvantages the _default_ `local` drivers has?
I fail to see the difference between this driver and the mounted host directory data container.

Thanks for your time!

**Comment by CWSpear** [comment]
The benefits/advantages are mentioned in the README: https://github.com/CWSpear/local-persist#benefits

But to reiterate: in your first example, I think there is some confusion. That isn't what I would call "using the default driver." Or, more specifically, you're not using named volumes.

So first, the benefits of using named volumes: if you use the directory just once and it's the same everywhere, it's not a big deal. But if you use it in multiple places (in your `docker-compose` config(s)), and it has a different location in development vs production, it becomes more of a burden to maintain. Using named volumes (i.e. the `data` in `volumes: data:/var/lib/mysql`), you only have to change/override the path in one place, and it will update for all containers using that named volume.

_This_ is what I would call using the default driver:

```yml
# docker-compose.yml
services:
  some-service:
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
```

This is still using a named volume, but it uses the default `local` driver since we didn't specify one. So I think you were on the right track with this one. The disadvantage with that is that you can't specify where the volume exists (it's a randomized folder), _and_ it won't persist if you remove the volume. That's where the _persist_ in `local-persist` comes from. With this plugin, you can `docker volume rm data` and it only deletes the volume reference to that folder and _not the data_, so then next time you `docker-compose up`, the data is still there.
