### ISSUE TITLE
Add one file mount support

### ISSUE THREAD

**Issue by kisdaniel** [CWSpear/local-persist#49]
I would like to mount only one file like this:

docker-compose.yml example:

```
version: '3'
services:
  nginx:
    image: nginx
    volumes:
       - nginx-configfile:/etc/nginx/nginx.conf
volumes:
  nginx-configfile:
    driver: local-persist
    driver_opts:
      mountpoint: /var/lib/docker-persistent-volume/nginx/config/nginx.conf
```
