### ISSUE TITLE
Mountpoint ignored?

### ISSUE THREAD

**Issue by mplx** [CWSpear/local-persist#56]
I'm stuck on the  `mountpoint` opt in my docker swarm - I'd like to mount `/mnt/app/volumes/data` but as `docker inspect` shows the source dir sticks to the stacks yml file directory...

- Expected: mount `/mnt/app/volumes/data` to `/data`
- Happening: mounted  `/mnt/app` to `/data`
- Docker version 17.10.0-ce (f4ffd25) on Debian Stretch
- md5sum /usr/bin/docker-volume-local-persist 815b4b931c92af3eb5417a74bf07fd35  

`cat /mnt/app/compose-stack.yml`

```yml
version: "3"

services:

  app:
    volumes:
      - appdata:/data
...

volumes:
  appdata:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/app/volumes/data
```

`docker stack deploy -c /mnt/app/compose-stack.yml app`

`docker inspect ID`

```yml
...
            {
                "Type": "volume",
                "Name": "app_appdata",
                "Source": "/mnt/app",
                "Destination": "/data",
                "Driver": "local-persist",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
...
```
